language: python
sudo: false

matrix:
  include:
    - os: linux
      arch: arm64
      language: generic
      env: PYTHON_VERSION=3.6
    - os: linux
      arch: arm64
      language: generic
      env: PYTHON_VERSION=3.7

before_install:
  # Install latest miniconda
  - SUDO=sudo;
  - wget -q "https://github.com/Archiconda/build-tools/releases/download/0.2.3/Archiconda3-0.2.3-Linux-aarch64.sh" -O archiconda.sh;
  - chmod +x archiconda.sh;
  - bash archiconda.sh -b -p $HOME/miniconda;
  - export PATH="$HOME/miniconda/bin:$PATH";
  - $SUDO cp -r $HOME/miniconda/bin/* /usr/bin/;
  - source "$HOME"/miniconda/etc/profile.d/conda.sh;
  - service activate;

install:
  - pip install -r requirements.txt
  - python setup.py install

script:
  - tox -v
