language: python
#sudo: false
addons:
  apt:
    packages:
    - tox
    - python3-dev
    - libpython3.7
    - wget

matrix:
  include:
    - os: linux
      dist: bionic
      language: python
      env: PYTHON_VERSION=3.7
    - os: linux
      dist: bionic
      arch: arm64
      language: python
      env: PYTHON_VERSION=3.7

before_install:
  # Install miniconda
  - if [ "${TRAVIS_CPU_ARCH}" == "arm64" ]; then
        wget https://github.com/conda-forge/miniforge/releases/download/4.8.2-1/Miniforge3-4.8.2-1-Linux-aarch64.sh -O miniconda.sh;
    else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - MINICONDA_PATH=/home/travis/miniconda
  - chmod +x miniconda.sh && ./miniconda.sh -b -p $MINICONDA_PATH
  - export PATH=$MINICONDA_PATH/bin:$PATH

# Configure the conda environment and put it in the path using the
# provided versions
  - conda create -n testenv --yes python=$PYTHON_VERSION pip
  - source activate testenv

install:
  - python setup.py install
  #- conda install hadoop-test-cluster==0.1.0 smbprotocol

script:
  - tox -e py37
